import { prisma } from "@/lib/prisma";
import { getUserId } from "@/lib/get-user";
import { NextResponse } from "next/server";

export async function POST() {
  const userId = await getUserId();
  if (!userId) return NextResponse.json({ error: "未授权" }, { status: 401 });

  const subscriptions = [
    {
      name: "LangSmith",
      platform: "LangSmith",
      plan: "Plus",
      amount: 39,
      currency: "USD",
      billingCycle: "monthly",
      status: "active",
      category: "ai",
      startDate: new Date("2025-01-15"),
      endDate: new Date("2026-05-15"),
      url: "https://smith.langchain.com",
      paymentMethod: "Visa ****1234",
      description: "LangChain 监控和调试平台",
      color: "#1c3c3c",
    },
    {
      name: "Supabase",
      platform: "Supabase",
      plan: "Pro",
      amount: 25,
      currency: "USD",
      billingCycle: "monthly",
      status: "active",
      category: "infrastructure",
      startDate: new Date("2024-06-01"),
      endDate: new Date("2026-05-01"),
      url: "https://supabase.com",
      paymentMethod: "Visa ****1234",
      description: "BaaS 数据库和认证服务",
      color: "#3ecf8e",
    },
    {
      name: "Vercel",
      platform: "Vercel",
      plan: "Pro",
      amount: 20,
      currency: "USD",
      billingCycle: "monthly",
      status: "active",
      category: "infrastructure",
      startDate: new Date("2024-03-10"),
      endDate: new Date("2026-04-20"),
      url: "https://vercel.com",
      paymentMethod: "PayPal",
      color: "#171717",
    },
    {
      name: "Claude Pro",
      platform: "Anthropic",
      plan: "Pro",
      amount: 20,
      currency: "USD",
      billingCycle: "monthly",
      status: "active",
      category: "ai",
      startDate: new Date("2025-03-01"),
      endDate: new Date("2026-05-01"),
      url: "https://claude.ai",
      paymentMethod: "Visa ****1234",
      description: "Anthropic Claude AI 助手",
      color: "#d97757",
    },
    {
      name: "GitHub Copilot",
      platform: "GitHub",
      plan: "Business",
      amount: 19,
      currency: "USD",
      billingCycle: "monthly",
      status: "active",
      category: "development",
      startDate: new Date("2024-08-01"),
      endDate: new Date("2026-05-01"),
      url: "https://github.com/features/copilot",
      paymentMethod: "Visa ****5678",
      color: "#1f2937",
    },
    {
      name: "Figma",
      platform: "Figma",
      plan: "Organization",
      amount: 45,
      currency: "USD",
      billingCycle: "monthly",
      status: "active",
      category: "design",
      startDate: new Date("2024-01-01"),
      endDate: new Date("2026-05-01"),
      url: "https://figma.com",
      paymentMethod: "Visa ****5678",
      color: "#a259ff",
    },
    {
      name: "Notion",
      platform: "Notion",
      plan: "Team",
      amount: 10,
      currency: "USD",
      billingCycle: "monthly",
      status: "active",
      category: "productivity",
      startDate: new Date("2024-04-01"),
      endDate: new Date("2026-05-01"),
      url: "https://notion.so",
      paymentMethod: "Visa ****1234",
      color: "#191919",
    },
    {
      name: "OpenAI API",
      platform: "OpenAI",
      plan: "Pay-as-you-go",
      amount: 120,
      currency: "USD",
      billingCycle: "monthly",
      status: "active",
      category: "ai",
      startDate: new Date("2024-01-01"),
      endDate: new Date("2026-05-01"),
      url: "https://platform.openai.com",
      paymentMethod: "Visa ****1234",
      description: "GPT-4 API 调用",
      color: "#10a37f",
    },
    {
      name: "Cloudflare Workers",
      platform: "Cloudflare",
      plan: "Workers Paid",
      amount: 5,
      currency: "USD",
      billingCycle: "monthly",
      status: "active",
      category: "infrastructure",
      startDate: new Date("2024-10-01"),
      endDate: new Date("2026-05-01"),
      url: "https://workers.cloudflare.com",
      color: "#f48120",
    },
    {
      name: "Linear",
      platform: "Linear",
      plan: "Plus",
      amount: 8,
      currency: "USD",
      billingCycle: "monthly",
      status: "active",
      category: "productivity",
      startDate: new Date("2025-02-01"),
      endDate: new Date("2026-05-01"),
      url: "https://linear.app",
      color: "#5e6ad2",
    },
    {
      name: "Slack",
      platform: "Slack",
      plan: "Pro",
      amount: 8.75,
      currency: "USD",
      billingCycle: "monthly",
      status: "active",
      category: "productivity",
      startDate: new Date("2024-07-01"),
      endDate: new Date("2026-05-01"),
      url: "https://slack.com",
      color: "#4a154b",
    },
    {
      name: "AWS S3",
      platform: "AWS",
      plan: "Standard",
      amount: 15,
      currency: "USD",
      billingCycle: "monthly",
      status: "active",
      category: "infrastructure",
      startDate: new Date("2024-01-01"),
      endDate: new Date("2026-05-01"),
      url: "https://aws.amazon.com",
      paymentMethod: "Visa ****9012",
      color: "#ff9900",
    },
  ];

  const results = [];
  for (const sub of subscriptions) {
    const result = await prisma.subscription.create({
      data: { userId, ...sub, remindDays: 7 },
    });
    results.push(result);
  }

  return NextResponse.json({ seeded: results.length });
}
